repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Backend specific hooks
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.11
        files: ^backend/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.11
        files: ^backend/.*

  # Frontend specific hooks
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint
        language: node
        types: [javascript]
        files: ^frontend/
        additional_dependencies: [eslint@7.32.0]
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types: [javascript, css, html]
        files: ^frontend/.*
        additional_dependencies: [prettier@2.3.2]
